# Generated by Django 5.1.6 on 2025-03-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CourseTitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='Department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
